name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest

      - name: Build
        run: echo "Build completed successfully"

      - name: Deploy
        run: echo "Application deployed successfully"
